import ASC = require("./src/ASC");
import Application = require("./src/Application");
import Assignment = require("./src/Assignment");
import Attachment = require("./src/Attachment");
import Class = require("./src/Class");
import Classroom = require("./src/Classroom");
import Edupage = require("./src/Edupage");
import Grade = require("./src/Grade");
import Homework = require("./src/Homework");
import Lesson = require("./src/Lesson");
import Message = require("./src/Message");
import Parent = require("./src/Parent");
import Period = require("./src/Period");
import Plan = require("./src/Plan");
import Season = require("./src/Season");
import Student = require("./src/Student");
import Subject = require("./src/Subject");
import Teacher = require("./src/Teacher");
import Test = require("./src/Test");
import Timetable = require("./src/Timetable");
import User = require("./src/User");
import { GENDER } from "./src/enums";
import { ENDPOINT } from "./src/enums";
import { ENTITY_TYPE } from "./src/enums";
import { API_STATUS } from "./src/enums";
import { ASSIGNMENT_TYPE } from "./src/enums";
import { ASSIGNMENT_GROUP } from "./src/enums";
import { TIMELINE_ITEM_TYPE } from "./src/enums";
import { LoginError } from "./src/exceptions";
import { ParseError } from "./src/exceptions";
import { EdupageError } from "./src/exceptions";
import { APIError } from "./src/exceptions";
import { MessageError } from "./src/exceptions";
import { AttachmentError } from "./src/exceptions";
import { FatalError } from "./src/exceptions";
export { ASC, Application, Assignment, Attachment, Class, Classroom, Edupage, Grade, Homework, Lesson, Message, Parent, Period, Plan, Season, Student, Subject, Teacher, Test, Timetable, User, GENDER, ENDPOINT, ENTITY_TYPE, API_STATUS, ASSIGNMENT_TYPE, ASSIGNMENT_GROUP, TIMELINE_ITEM_TYPE, LoginError, ParseError, EdupageError, APIError, MessageError, AttachmentError, FatalError };
